default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/pipeline-validation-hooks
    rev: 978b3be344b6e93ca41293f1fc947cc5f557c2cb
    hooks:
    -   id: consistency_checks
        name: consistency_checks
        entry: pipeline_validation_hooks/consistency_checks.py
        language: script
        verbose: true
    -   id: formatting
        name: formatting
        entry: pipeline_validation_hooks/formatting.py
        language: script
