params:
    HASH_ID_FUNCTION: 'v_0.3'
    BATCH_SIZE: 500
    MERGING_THRESHOLDs: [0.7, 0.95]
    SCREEN: NONE|PRE_SCREEN|INCLUSION_SCREEN
    DATA: NONE|CSV_TABLE|MD_SHEETS|MA_VARIABLES_CSV
    PDF_HANDLING: EXT|GIT
    SHARE_STATUS_REQUIREMENT: NONE|PROCESSED|SCREENED|COMPLETED
