params:
  HASH_ID_FUNCTION: 'v_0.3'
  BATCH_SIZE: 2000
  MERGING_DUP_THRESHOLD: 0.95
  MERGING_NON_DUP_THRESHOLD: 0.7
  DELAY_AUTOMATED_PROCESSING: True
  SCREEN: INCLUSION_SCREEN
  DATA: CSV_TABLE
  PDF_HANDLING: EXT
  SHARE_STATUS_REQUIREMENT: PROCESSED
