params:
  HASH_ID_FUNCTION: 'v_0.3'
  BATCH_SIZE: 2000
  MERGING_DUP_THRESHOLD: 0.95
  MERGING_NON_DUP_THRESHOLD: 0.7
  DELAY_AUTOMATED_PROCESSING: True
  SCREEN: SCREEN_TYPE
  DATA_FORMAT: DATA_FORMAT
  PDF_HANDLING: PDF_HANDLING_VALUE
  SHARE_STATUS_REQUIREMENT: SHARE_STAT_REQ
