[tool.poetry]
name = "colrev.get_masterdata_from_doi"
description = "CoLRev package for doi_metadata_prep"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/get_masterdata_from_doi/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "experimental"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
prep = "colrev.packages.get_masterdata_from_doi.src.doi_metadata_prep:DOIMetadataPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
