[project]
name = "colrev.blank"
description = "CoLRev package for blank_review"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "stable"
review_type = "colrev.packages.blank.src.blank:BlankReview"
