[tool.poetry]
name = "colrev"
version = "0.12.3"
description = "CoLRev: An open-source environment for collaborative reviews"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>", "Julian Prester <julian.prester@sydney.edu.au>"]
license = "MIT"
readme = "README.md"
homepage="https://colrev-environment.github.io/colrev/"
repository = "https://github.com/CoLRev-Environment/colrev"
documentation = "https://colrev-environment.github.io/colrev/"
keywords = ["research", "reproducible research", "open science", "literature", "literature review", "systematic review", "systematic literature review"]
classifiers = [
   "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
include = ["CONTRIBUTING.md", "CHANGELOG.md", "LICENSE", "README.md", "colrev/py.typed"]

[tool.poetry.scripts]
colrev = "colrev.ui_cli.cli:main"
colrev-hooks-check = "colrev.hooks.check:main"
colrev-hooks-format = "colrev.hooks.format:main"
colrev-hooks-report = "colrev.hooks.report:main"
colrev-hooks-share = "colrev.hooks.share:main"
colrev-hooks-update = "colrev.hooks.update:main"

[tool.poetry.dependencies]
python = ">=3.9, <4"
click = "^8.1.6"
click_completion = "^0.5.2"
click-repl = "^0.3.0"
inquirer = "^3.1.3"
glom = "^22.1.0"
Jinja2 = "^3.1.2"
tqdm = "^4.64.1"
GitPython= "^3.1.29"
pre-commit = "^2.20.0"
"zope.interface" = "^5.5.0"
dacite = "^1.6.0"
dataclasses-jsonschema = "^2.15.3"
dictdiffer = "^0.9.0"
imagehash = "^4.3.1"
rapidfuzz = "^3.5.2"
bib-dedupe = "^0.7.6"
docker = "6.0.0"
lxml = "^4.9.1"
pandas = "^1.5.0"
openpyxl = "^3.1.2"   # required by pandas for Excel
PyYAML = "^6.0.0"
feedparser = "^6.0.10"       # internally?
pybtex = "^0.24.0"           # internally?
requests = "<2.32.0"
urllib3 = "<2.0" # https://github.com/google-deepmind/alphafold/issues/867
requests-cache = "^0.9.6"
lingua-language-detector = "^2.0.2"
pycountry = "^22.3.5"
nameparser = "^1.1.2"
number-parser = "^0.3.2"
pymupdf = "^1.24.3"
m2r = "^0.3.1"
toml = "^0.10.2"
Sphinx = {version = "^5.2.3", optional = true }
sphinx-autodoc-typehints = {version = "^1.19.4", optional = true }
sphinx-click = {version = "^4.3.0", optional = true }
sphinx-rtd-theme = {version = "^1.1.1", optional = true }
sphinx-copybutton = {version = "^0.5.2", optional = true}
"sphinxcontrib.datatemplates" = {version = "^0.9.2", optional = true }
sphinx-design = {version = "^0.5.0", optional = true }
sphinx_collapse = {version = "^0.1.2", optional = true }
repoze-sphinx-autointerface = {version = "^1.0.0", optional = true }
pylint = {version = "3.0.1", optional = true }
pytest = {version = "^7.2.1", optional = true }
pytest-mock = {version = "^3.10.0", optional = true }
pytest-skip-slow = {version = "^0.0.5", optional = true }
requests-mock = {version = "^1.10.0", optional = true }
coverage = {extras = ["toml"], version = "^7.3.2", optional = true }
types-click = {version = "^7.1.8", optional = true }
# Can't do 0.21 with poetry because of https://github.com/python-poetry/poetry/issues/9293
docutils = {version = "!=0.21.post1", optional = true }
"colrev.ui_web" = {path = "./colrev/packages/ui_web", optional = true}
"colrev.local_index" = {path="./colrev/packages/local_index", optional = true}
"colrev.exclude_non_latin_alphabets" = {path="./colrev/packages/exclude_non_latin_alphabets", optional = true}
"colrev.dedupe" = {path="./colrev/packages/dedupe", optional = true}
"colrev.meta_analysis" = {path="./colrev/packages/meta_analysis", optional = true}
"colrev.colrev_cli_pdf_get_man" = {path="./colrev/packages/colrev_cli_pdf_get_man", optional = true}
"colrev.acm_digital_library" = {path="./colrev/packages/acm_digital_library", optional = true}
"colrev.ebsco_host" = {path="./colrev/packages/ebsco_host", optional = true}
"colrev.jstor" = {path="./colrev/packages/jstor", optional = true}
"colrev.remove_last_page" = {path="./colrev/packages/remove_last_page", optional = true}
"colrev.scope_prescreen" = {path="./colrev/packages/scope_prescreen", optional = true}
"colrev.descriptive_review" = {path="./colrev/packages/descriptive_review", optional = true}
"colrev.genai" = {path="./colrev/packages/genai", optional = true}
"colrev.ocrmypdf" = {path="./colrev/packages/ocrmypdf", optional = true}
"colrev.sync" = {path="./colrev/packages/sync", optional = true}
"colrev.web_of_science" = {path="./colrev/packages/web_of_science", optional = true}
"colrev.website_screenshot" = {path="./colrev/packages/website_screenshot", optional = true}
"colrev.crossref" = {path="./colrev/packages/crossref", optional = true}
"colrev.paper_md" = {path="./colrev/packages/paper_md", optional = true}
"colrev.scopus" = {path="./colrev/packages/scopus", optional = true}
"colrev.grobid_tei" = {path="./colrev/packages/grobid_tei", optional = true}
"colrev.pdf_backward_search" = {path="./colrev/packages/pdf_backward_search", optional = true}
"colrev.export_man_prep" = {path="./colrev/packages/export_man_prep", optional = true}
"colrev.files_dir" = {path="./colrev/packages/files_dir", optional = true}
"colrev.eric" = {path="./colrev/packages/eric", optional = true}
"colrev.prep_man_curation_jupyter" = {path="./colrev/packages/prep_man_curation_jupyter", optional = true}
"colrev.critical_review" = {path="./colrev/packages/critical_review", optional = true}
"colrev.exclude_languages" = {path="./colrev/packages/exclude_languages", optional = true}
"colrev.google_scholar" = {path="./colrev/packages/google_scholar", optional = true}
"colrev.colrev_curation" = {path="./colrev/packages/colrev_curation", optional = true}
"colrev.open_alex" = {path="./colrev/packages/open_alex", optional = true}
"colrev.curation_full_outlet_dedupe" = {path="./colrev/packages/curation_full_outlet_dedupe", optional = true}
"colrev.europe_pmc" = {path="./colrev/packages/europe_pmc", optional = true}
"colrev.theoretical_review" = {path="./colrev/packages/theoretical_review", optional = true}
"colrev.open_library" = {path="./colrev/packages/open_library", optional = true}
"colrev.colrev_project" = {path="./colrev/packages/colrev_project", optional = true}
"colrev.add_journal_ranking" = {path="./colrev/packages/add_journal_ranking", optional = true}
"colrev.psycinfo" = {path="./colrev/packages/psycinfo", optional = true}
"colrev.get_masterdata_from_citeas" = {path="./colrev/packages/get_masterdata_from_citeas", optional = true}
"colrev.taylor_and_francis" = {path="./colrev/packages/taylor_and_francis", optional = true}
"colrev.unpaywall" = {path="./colrev/packages/unpaywall", optional = true}
"colrev.remove_broken_ids" = {path="./colrev/packages/remove_broken_ids", optional = true}
"colrev.ieee" = {path="./colrev/packages/ieee", optional = true}
"colrev.source_specific_prep" = {path="./colrev/packages/source_specific_prep", optional = true}
"colrev.umbrella" = {path="./colrev/packages/umbrella", optional = true}
"colrev.springer_link" = {path="./colrev/packages/springer_link", optional = true}
"colrev.general_polish" = {path="./colrev/packages/general_polish", optional = true}
"colrev.curated_masterdata" = {path="./colrev/packages/curated_masterdata", optional = true}
"colrev.remove_urls_with_500_errors" = {path="./colrev/packages/remove_urls_with_500_errors", optional = true}
"colrev.qualitative_systematic_review" = {path="./colrev/packages/qualitative_systematic_review", optional = true}
"colrev.colrev_cli_prescreen" = {path="./colrev/packages/colrev_cli_prescreen", optional = true}
"colrev.dblp" = {path="./colrev/packages/dblp", optional = true}
"colrev.bibliography_export" = {path="./colrev/packages/bibliography_export", optional = true}
"colrev.arxiv" = {path="./colrev/packages/arxiv", optional = true}
"colrev.conceptual_review" = {path="./colrev/packages/conceptual_review", optional = true}
"colrev.doi_org" = {path="./colrev/packages/doi_org", optional = true}
"colrev.github_pages" = {path="./colrev/packages/github_pages", optional = true}
"colrev.download_from_website" = {path="./colrev/packages/download_from_website", optional = true}
"colrev.get_year_from_vol_iss_jour" = {path="./colrev/packages/get_year_from_vol_iss_jour", optional = true}
"colrev.pubmed" = {path="./colrev/packages/pubmed", optional = true}
"colrev.blank" = {path="./colrev/packages/blank", optional = true}
"colrev.exclude_collections" = {path="./colrev/packages/exclude_collections", optional = true}
"colrev.curation_missing_dedupe" = {path="./colrev/packages/curation_missing_dedupe", optional = true}
"colrev.ais_library" = {path="./colrev/packages/ais_library", optional = true}
"colrev.semanticscholar" = {path="./colrev/packages/semanticscholar", optional = true}
"colrev.abi_inform_proquest" = {path="./colrev/packages/abi_inform_proquest", optional = true}
"colrev.scientometric" = {path="./colrev/packages/scientometric", optional = true}
"colrev.remove_coverpage" = {path="./colrev/packages/remove_coverpage", optional = true}
"colrev.scoping_review" = {path="./colrev/packages/scoping_review", optional = true}
"colrev.get_doi_from_urls" = {path="./colrev/packages/get_doi_from_urls", optional = true}
"colrev.prescreen_table" = {path="./colrev/packages/prescreen_table", optional = true}
"colrev.obsidian" = {path="./colrev/packages/obsidian", optional = true}
"colrev.colrev_cli_screen" = {path="./colrev/packages/colrev_cli_screen", optional = true}
"colrev.synergy_datasets" = {path="./colrev/packages/synergy_datasets", optional = true}
"colrev.get_masterdata_from_doi" = {path="./colrev/packages/get_masterdata_from_doi", optional = true}
"colrev.trid" = {path="./colrev/packages/trid", optional = true}
"colrev.wiley" = {path="./colrev/packages/wiley", optional = true}
"colrev.exclude_complementary_materials" = {path="./colrev/packages/exclude_complementary_materials", optional = true}
"colrev.narrative_review" = {path="./colrev/packages/narrative_review", optional = true}
"colrev.conditional_prescreen" = {path="./colrev/packages/conditional_prescreen", optional = true}
"colrev.structured" = {path="./colrev/packages/structured", optional = true}
"colrev.unknown_source" = {path="./colrev/packages/unknown_source", optional = true}
"colrev.literature_review" = {path="./colrev/packages/literature_review", optional = true}
"colrev.colrev_cli_pdf_prep_man" = {path="./colrev/packages/colrev_cli_pdf_prep_man", optional = true}
"colrev.prisma" = {path="./colrev/packages/prisma", optional = true}
"colrev.screen_table" = {path="./colrev/packages/screen_table", optional = true}
"colrev.open_citations_forward_search" = {path="./colrev/packages/open_citations_forward_search", optional = true}
"colrev.profile" = {path="./colrev/packages/profile", optional = true}
"colrev.methodological_review" = {path="./colrev/packages/methodological_review", optional = true}
"colrev.osf" = {path="./colrev/packages/osf", optional = true}
"colrev.github" = {path="./colrev/packages/github", optional = true}

[tool.poetry.extras]
"colrev.abi_inform_proquest" = ["colrev.abi_inform_proquest"]
"colrev.acm_digital_library" = ["colrev.acm_digital_library"]
"colrev.add_journal_ranking" = ["colrev.add_journal_ranking"]
"colrev.ais_library" = ["colrev.ais_library"]
"colrev.arxiv" = ["colrev.arxiv"]
"colrev.bibliography_export" = ["colrev.bibliography_export"]
"colrev.blank" = ["colrev.blank"]
"colrev.colrev_cli_pdf_get_man" = ["colrev.colrev_cli_pdf_get_man"]
"colrev.colrev_cli_pdf_prep_man" = ["colrev.colrev_cli_pdf_prep_man"]
"colrev.colrev_cli_prescreen" = ["colrev.colrev_cli_prescreen"]
"colrev.colrev_cli_screen" = ["colrev.colrev_cli_screen"]
"colrev.colrev_curation" = ["colrev.colrev_curation"]
"colrev.colrev_project" = ["colrev.colrev_project"]
"colrev.conceptual_review" = ["colrev.conceptual_review"]
"colrev.conditional_prescreen" = ["colrev.conditional_prescreen"]
"colrev.critical_review" = ["colrev.critical_review"]
"colrev.crossref" = ["colrev.crossref"]
"colrev.curated_masterdata" = ["colrev.curated_masterdata"]
"colrev.curation_full_outlet_dedupe" = ["colrev.curation_full_outlet_dedupe"]
"colrev.curation_missing_dedupe" = ["colrev.curation_missing_dedupe"]
"colrev.dblp" = ["colrev.dblp"]
"colrev.dedupe" = ["colrev.dedupe"]
"colrev.descriptive_review" = ["colrev.descriptive_review"]
"colrev.doi_org" = ["colrev.doi_org"]
"colrev.download_from_website" = ["colrev.download_from_website"]
"colrev.ebsco_host" = ["colrev.ebsco_host"]
"colrev.eric" = ["colrev.eric"]
"colrev.europe_pmc" = ["colrev.europe_pmc"]
"colrev.exclude_collections" = ["colrev.exclude_collections"]
"colrev.exclude_complementary_materials" = ["colrev.exclude_complementary_materials"]
"colrev.exclude_languages" = ["colrev.exclude_languages"]
"colrev.exclude_non_latin_alphabets" = ["colrev.exclude_non_latin_alphabets"]
"colrev.export_man_prep" = ["colrev.export_man_prep"]
"colrev.files_dir" = ["colrev.files_dir"]
"colrev.genai" = ["colrev.genai"]
"colrev.general_polish" = ["colrev.general_polish"]
"colrev.get_doi_from_urls" = ["colrev.get_doi_from_urls"]
"colrev.get_masterdata_from_citeas" = ["colrev.get_masterdata_from_citeas"]
"colrev.get_masterdata_from_doi" = ["colrev.get_masterdata_from_doi"]
"colrev.get_year_from_vol_iss_jour" = ["colrev.get_year_from_vol_iss_jour"]
"colrev.github" = ["colrev.github"]
"colrev.github_pages" = ["colrev.github_pages"]
"colrev.google_scholar" = ["colrev.google_scholar"]
"colrev.grobid_tei" = ["colrev.grobid_tei"]
"colrev.ieee" = ["colrev.ieee"]
"colrev.jstor" = ["colrev.jstor"]
"colrev.literature_review" = ["colrev.literature_review"]
"colrev.local_index" = ["colrev.local_index"]
"colrev.meta_analysis" = ["colrev.meta_analysis"]
"colrev.methodological_review" = ["colrev.methodological_review"]
"colrev.narrative_review" = ["colrev.narrative_review"]
"colrev.obsidian" = ["colrev.obsidian"]
"colrev.ocrmypdf" = ["colrev.ocrmypdf"]
"colrev.open_alex" = ["colrev.open_alex"]
"colrev.open_citations_forward_search" = ["colrev.open_citations_forward_search"]
"colrev.open_library" = ["colrev.open_library"]
"colrev.osf" = ["colrev.osf"]
"colrev.paper_md" = ["colrev.paper_md"]
"colrev.pdf_backward_search" = ["colrev.pdf_backward_search"]
"colrev.prep_man_curation_jupyter" = ["colrev.prep_man_curation_jupyter"]
"colrev.prescreen_table" = ["colrev.prescreen_table"]
"colrev.prisma" = ["colrev.prisma"]
"colrev.profile" = ["colrev.profile"]
"colrev.psycinfo" = ["colrev.psycinfo"]
"colrev.pubmed" = ["colrev.pubmed"]
"colrev.qualitative_systematic_review" = ["colrev.qualitative_systematic_review"]
"colrev.remove_broken_ids" = ["colrev.remove_broken_ids"]
"colrev.remove_coverpage" = ["colrev.remove_coverpage"]
"colrev.remove_last_page" = ["colrev.remove_last_page"]
"colrev.remove_urls_with_500_errors" = ["colrev.remove_urls_with_500_errors"]
"colrev.scientometric" = ["colrev.scientometric"]
"colrev.scope_prescreen" = ["colrev.scope_prescreen"]
"colrev.scoping_review" = ["colrev.scoping_review"]
"colrev.scopus" = ["colrev.scopus"]
"colrev.screen_table" = ["colrev.screen_table"]
"colrev.semanticscholar" = ["colrev.semanticscholar"]
"colrev.source_specific_prep" = ["colrev.source_specific_prep"]
"colrev.springer_link" = ["colrev.springer_link"]
"colrev.structured" = ["colrev.structured"]
"colrev.sync" = ["colrev.sync"]
"colrev.synergy_datasets" = ["colrev.synergy_datasets"]
"colrev.taylor_and_francis" = ["colrev.taylor_and_francis"]
"colrev.theoretical_review" = ["colrev.theoretical_review"]
"colrev.trid" = ["colrev.trid"]
"colrev.ui_web" = ["colrev.ui_web"]
"colrev.umbrella" = ["colrev.umbrella"]
"colrev.unknown_source" = ["colrev.unknown_source"]
"colrev.unpaywall" = ["colrev.unpaywall"]
"colrev.web_of_science" = ["colrev.web_of_science"]
"colrev.website_screenshot" = ["colrev.website_screenshot"]
"colrev.wiley" = ["colrev.wiley"]
docs = ["Sphinx", "sphinx-autodoc-typehints", "sphinx-click", "sphinx-rtd-theme", "sphinxcontrib.datatemplates", "sphinx_collapse", "repoze-sphinx-autointerface", "sphinx-design", "sphinx-copybutton", "docutils"]
dev = ["pylint", "pytest", "coverage", "types-click", "pytest-mock", "requests-mock", "pytest-skip-slow"]
tests = ["colrev.literature_review", "colrev.files_dir", "colrev.export_man_prep", "colrev.dedupe", "colrev.colrev_cli_prescreen", "colrev.local_index", "colrev.unpaywall", "colrev.download_from_website", "colrev.colrev_cli_pdf_get_man", "colrev.ocrmypdf", "colrev.remove_coverpage", "colrev.remove_last_page", "colrev.grobid_tei", "colrev.colrev_cli_pdf_prep_man", "colrev.colrev_cli_screen", "colrev.paper_md", "colrev.source_specific_prep", "colrev.exclude_non_latin_alphabets", "colrev.exclude_collections", "colrev.exclude_complementary_materials", "colrev.local_index", "colrev.exclude_languages", "colrev.remove_urls_with_500_errors", "colrev.remove_broken_ids", "colrev.get_doi_from_urls", "colrev.get_year_from_vol_iss_jour", "colrev.crossref", "colrev.pubmed", "colrev.europe_pmc", "colrev.dblp", "colrev.open_library", "colrev.unknown_source", "colrev.conditional_prescreen", "colrev.psycinfo", "colrev.springer_link", "colrev.acm_digital_library", "colrev.abi_inform_proquest", "colrev.scopus", "colrev.taylor_and_francis", "colrev.web_of_science", "colrev.wiley", "colrev.trid", "colrev.jstor", "colrev.ebsco_host", "colrev.google_scholar", "colrev.eric", "colrev.ais_library", "colrev.ieee"]

[tool.mypy]
python_version = 3.8
warn_unused_configs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "requests.*",
    "yaml.*",
    "pkg_resources.*",
]
ignore_missing_imports = true

[tool.pylint.MAIN]
extension-pkg-whitelist = "lxml.etree"
load-plugins = ["colrev.linter.colrev_direct_status_assign", "colrev.linter.colrev_missed_constant_usage", "colrev.linter.colrev_records_variable_naming_convention"]

[tool.pylint.'MESSAGES CONTROL']
disable = ["R0801"]

[tool.coverage.report]
omit = [
    "colrev/packages/*", # omit reference implementation
    "/usr/*", # omit everything in /usr
    "*crossrefapi/crossref/*",
    "colrev/env/grobid_service.py",
    "/tmp/*",
    "tests/*",
    "*/bib-dedupe/bib_dedupe/*",
]

[tool.coverage.run]
omit = [
    "colrev/packages/*", # omit reference implementation
    "/usr/*", # omit everything in /usr
    "*crossrefapi/crossref/*",
    "colrev/env/grobid_service.py",
    "colrev/ops/upgrade.py",
    "/tmp/*",
    "tests/*",
    "*/bib-dedupe/bib_dedupe/*",
]

[tool.ruff]
line-length = 160

[build-system]
# requires = ["poetry>=1.2.0b1"]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
