[project]
name = "colrev.ref_check"
description = "Checks the quality of reference metadata"
version = "0.1.0"
license = "MIT"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/"

[tool.poetry.dependencies]
python = ">=3.9, <4"

[tool.colrev]
colrev_doc_description = "TODO"
colrev_doc_link = "docs/README.md"
search_types = []

[project.entry-points."colrev"]
data = "colrev.packages.ref_check.src.ref_check:RefCheck"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
