[tool.poetry]
name = "colrev.taylor_and_francis"
description = "CoLRev package for taylor_and_francis"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/taylor_and_francis/TODO/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "experimental"
documentation = "README.md"
colrev_doc_link = "README.md"
search_source = "colrev.packages.taylor_and_francis.src.taylor_and_francis:TaylorAndFrancisSearchSource"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
