[project]
name = "colrev.eric"
description = "CoLRev package for eric"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>",
    "Rhea Nguyen",
    "Malou Schmidt",
    "Frederic Fischer",
    "Janus Fiegen",
    "Albert Borchardt"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/eric"

[tool.colrev]
colrev_doc_description = "ERIC API"
colrev_doc_link = "README.md"
search_types = ["API"]

[project.entry-points."colrev"]
search_source = "colrev.packages.eric.src.eric:ERICSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
