[project]
name = "colrev.meta_analysis"
description = "CoLRev package for meta-analysis"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/meta_analysis"

[tool.colrev]
colrev_doc_description = "Meta-Analysis"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points."colrev"]
review_type = "colrev.packages.meta_analysis.src.meta_analysis:MetaAnalysis"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
