[tool.poetry]
name = "colrev.literature_review"
description = "CoLRev package for literature_review"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/literature_review"

[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "stable"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
review_type = "colrev.packages.literature_review.src.literature_review:LiteratureReview"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
