[project]
name = "colrev.literature_review"
description = "CoLRev package for literature_review"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/literature_review"

[tool.colrev]
colrev_doc_description = "Literature Review"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points."colrev"]
review_type = "colrev.packages.literature_review.src.literature_review:LiteratureReview"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
