[tool.poetry]
name = "colrev.get_year_from_vol_iss_jour"
description = "CoLRev package for year_vol_iss_prep"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/get_year_from_vol_iss_jour/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "experimental"
documentation = "README.md"
colrev_doc_link = "README.md"
prep = "colrev.packages.get_year_from_vol_iss_jour.src.year_vol_iss_prep:YearVolIssPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
