[project]
name = "colrev.plos"
description = ""
version = "0.1.0"
license = "MIT"
authors = ["olgagirona <olga.girona-cutillas@stud.uni-bamberg.de>"]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/"

[tool.colrev]
colrev_doc_description = "TODO"
colrev_doc_link = "docs/README.md"
search_types = []

[project.entry-points."colrev"]
search_source = "colrev.packages.plos.src.plos_search_source:PlosSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
