[tool.poetry]
name = "colrev.abi_inform_proquest"
description = "CoLRev package for abi_inform_proquest"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/abi_inform_proquest/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
documentation = "README.md"
colrev_doc_link = "README.md"
dev_status = "experimental"
search_source = "colrev.packages.abi_inform_proquest.src.abi_inform_proquest:ABIInformProQuestSearchSource"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
