[tool.poetry]
name = "colrev.remove_urls_with_500_errors"
description = "CoLRev package for remove_urls_with_500_errors"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/remove_urls_with_500_errors/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
prep = "colrev.packages.remove_urls_with_500_errors.src.remove_urls_with_500_errors:RemoveError500URLsPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
