[tool.poetry]
name = "colrev.colrev_cli_pdf_get_man"
description = "CoLRev package for pdf_get_man_cli"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/colrev_cli_pdf_get_man/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
pdf_get_man = "colrev.packages.colrev_cli_pdf_get_man.src.pdf_get_man_cli:CoLRevCLIPDFGetMan"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
