[tool.poetry]
name = "colrev.pubmed"
description = "CoLRev package for pubmed"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/pubmed/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"
search_source = "colrev.packages.pubmed.src.pubmed:PubMedSearchSource"
prep = "colrev.packages.pubmed.src.pubmed_metadata_prep:PubmedMetadataPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
