[tool.poetry]
name = "colrev.crossref"
description = "Crossref package for CoLRev"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/crossref/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"
search_source = "colrev.packages.crossref.src.crossref_search_source:CrossrefSearchSource"
prep = "colrev.packages.crossref.src.crossref_prep:CrossrefMetadataPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
