[tool.poetry]
name = "colrev.ui_web"
description = "Web-UI package for CoLRev"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/ui_web/README.md"

[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"
dash = "^2.11.1"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"

[build-system]
# requires = ["poetry>=1.2.0b1"]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"