[tool.poetry]
name = "colrev.colrev_curation"
description = "CoLRev package for colrev_curation"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/colrev_curation/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"
data = "colrev.packages.colrev_curation.src.colrev_curation:ColrevCuration"
prep = "colrev.packages.colrev_curation.src.curation_prep:CurationPrep"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
