[tool.poetry]
name = "colrev.curation_missing_dedupe"
description = "CoLRev package for curation_missing_dedupe"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/curation_missing_dedupe/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "experimental"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
dedupe = "colrev.packages.curation_missing_dedupe.src.curation_missing_dedupe:CurationMissingDedupe"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
