[project]
name = "colrev.trid"
description = "CoLRev package for trid"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/trid"

[tool.colrev]
colrev_doc_description = "Transport Research International Documentation"
colrev_doc_link = "README.md"
search_types = ["DB"]

[project.entry-points."colrev"]
search_source = "colrev.packages.trid.src.trid:TransportResearchInternationalDocumentation"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
