[project]
name = "colrev.osf"
description = "CoLRev package for osf"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
]
documentation = "README.md"

[tool.colrev]
dev_status = "experimental"
search_source = "colrev.packages.osf.src.osf:OSFSearchSource"
colrev_doc_link = "README.md"
