[project]
name = "colrev.prospero"
description = "ColRev package for Prospero"
version = "0.1.0"
license = "MIT"
authors = [
"Ammar Al-Balkhi <ammar.al-balkhi@stud.uni-bamberg.de>",
"Phuc Tran <tra-thien-phuc.tran@stud.uni-bamberg.de>",
"Olha Komashevska <olha.komashevska@stud.uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/"
selenium = "^4.27.1"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "TODO"
colrev_doc_link = "docs/README.md"
search_types = ["API"]

[project.entry-points."colrev"]
search_source ="colrev.packages.prospero.src.prospero_search_source:ProsperoSearchSource"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
