[tool.poetry]
name = "colrev.web_of_science"
description = "CoLRev package for web_of_science"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/web_of_science/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "experimental"
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.poetry.plugins.colrev]
search_source = "colrev.packages.web_of_science.src.web_of_science:WebOfScienceSearchSource"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
