[project]
name = "colrev.web_of_science"
description = "CoLRev package for web_of_science"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/web_of_science"

[tool.colrev]
colrev_doc_description = "Web of Science"
colrev_doc_link = "README.md"
search_types = ["DB"]

[project.entry-points."colrev"]
search_source = "colrev.packages.web_of_science.src.web_of_science:WebOfScienceSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
