[tool.poetry]
name = "colrev.colrev_cli_prescreen"
description = "CoLRev package for colrev_cli_prescreen"
version = "0.1.0"
authors = ["Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
license = "MIT"
documentation = "https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/colrev_cli_prescreen/README.md"


[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"

[tool.colrev]
dev_status = "maturing"
documentation = "README.md"
colrev_doc_link = "README.md"
prescreen = "colrev.packages.colrev_cli_prescreen.src.prescreen_cli:CoLRevCLIPrescreen"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
