[project]
name = "colrev.github_pages"
description = "CoLRev package for github_pages"
version = "0.1.0"
license = "MIT"
authors = [
    "Julian Prester <julian.prester@sydney.edu.au>",
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/github_pages"

[tool.colrev]
colrev_doc_description = "GitHub pages"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points."colrev"]
data = "colrev.packages.github_pages.src.github_pages:GithubPages"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
