[project]
name = "colrev.genai"
description = "CoLRev package for GenAI"
version = "0.1.0"
authors = [
    { name = "Julian Prester", email = "julian.prester@sydney.edu.au" },
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
]
documentation = "README.md"
colrev_doc_link = "README.md"

[tool.colrev]
dev_status = "experimental"
prescreen = "colrev.packages.genai.src.genai_prescreen:GenAIPrescreen"
screen = "colrev.packages.genai.src.genai_screen:GenAIScreen"
