[tool.poetry]
name = "colrev.genai"
description = "CoLRev package for GenAI"
version = "0.1.0"
license = "MIT"
authors = ["Julian Prester <julian.prester@sydney.edu.au>", "Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/genai"

[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"
litellm = "^1.37.0"
pydantic = "^2.7.1"

[tool.colrev]
colrev_doc_description = "GenAI"
colrev_doc_link = "README.md"
search_types = []

[tool.poetry.plugins.colrev]
prescreen = "colrev.packages.genai.src.genai_prescreen:GenAIPrescreen"
screen = "colrev.packages.genai.src.genai_screen:GenAIScreen"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"
